### ISSUE TITLE
Dependency conflict with tensorflow 2.12 because of numpy>=1.24.2 requirement

### ISSUE THREAD

**Issue by kvrban** [ClementPerroud/Gym-Trading-Env#1]
Hi, on colab tensorflow 2.12 is default. And Gym-Trading-Env has a numpy>=1.24.2 requirement.  But this end in a dependency conflicts:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.
```

Question: Is numpy>=1.24.2 mandatory for Gym-Trading-Env?

**Comment by ClementPerroud** [comment]
Hi, for now, you can try to update pip using:
`pip install --upgrade pip`
Then `!pip install gym-trading-env` should work (it worked for me at least)

**Comment by kvrban** [comment]
A pip upgrade does not change the issue. But the dependency conflict with numpy 1.24.3 is more a less just unpleasant. You can import gym-trading-env

But colab behaves odd when looping the observation space. It get stuck in:

```
while not done and not truncated:
    action = env.action_space.sample()
    observation, reward, done, truncated, info = env.step(action)
print(info)
```
You can check: 
https://colab.research.google.com/drive/12AxChYkE-I1Q1JqC_eThQzGMP3wStqEb?usp=sharing

(edit new link to colab)

**Comment by kvrban** [comment]
Maybe i just run out of "compute units" on colab... If it works fine for you in this colab? Then close this issue. But the dependency conflict with numpy is unpleasant if you share code samples in colab. Therefore the original question / suggestion if numpy>=1.24.2 is mandatory.

**Comment by ClementPerroud** [comment]
Hi thank you for the reply. Indeed, I am sorry, I misunderstood the issue. I fixed the conflict by lowering the version of Numpy needed ;)
